Adding PineH64 SBC support
adafruit/Adafruit_Blinka pull request #322
Opened 2020-07-23 15:54 UTC by dmanla

I have added the "microcontroller" file and "board" file for the Allwinner H6 based PineH64. I believe these are the only necessary files for Blinka compatibility.

I followed the guide provided by Adafruit at the following link: 
https://learn.adafruit.com/adding-a-single-board-computer-to-blinka/

I will also be creating a pull request for adafruit_platformdetect to add PineH64 detection.

2020-07-23 16:28 UTC, dmanla commented
Good afternoon,

I noticed my pull request has failed the check due to a formatting issue. I am unsure what this issue is. When creating the file I used the pine64.py file as a reference. I see no discrepancies in their formatting.

2020-07-23 16:51 UTC, makermelissa commented
Thanks. You will probably also need to add an `elif` line to board.py and the checks will fail until your PlatformDetect PR is in.

2020-08-05 18:58 UTC, dmanla commented
PineH64 has now been added to the large elsif block.

2020-08-05 20:12 UTC, makermelissa commented
Looks like you're missing an asterisk at the end of your import statement.

2020-10-12 22:20 UTC, makermelissa requested changes

2020-10-12 22:20 UTC, makermelissa commented on src/board.py
> +    from adafruit_blinka.board.pineH64 import
This line should be:
`from adafruit_blinka.board.pineH64 import *`

2020-10-14 19:28 UTC, dmanla commented
Hey, 

Sorry for the super long wait. I added the asterisk.

2020-10-14 20:06 UTC, makermelissa commented
Thanks for following up. We need to get https://github.com/adafruit/Adafruit_Python_PlatformDetect/pull/90 merged in before this will pass and there's some long comment lines stopping it from passing the checks.

2020-11-01 17:48 UTC, makermelissa approved these changes
This looks good.

2020-11-01 17:49 UTC, merged