Add support for ftdi URLs in the BLINKA_FT232H variable.
adafruit/Adafruit_Blinka pull request #436
Opened 2021-03-25 04:55 UTC by renpytom

This allows the an FTDI URL, like ftdi://ftdi:232h:W00001/1
to be given in the BLINKA_FT232H. If it's used, then that
board is the one that is opened. If the value of the variable
is not an FTDI url, then the default is used.

This makes it possible for multiple processes on the same
computer to talk to different FTDI boards. While talking
to multiple boards from a single process might be possible,
that's outside of the scope of this commit.

2021-03-27 23:04 UTC, ladyada commented
seems nifty to me

@caternuson or @makermelissa one of ya wanna test to make sure it still works?

2021-03-28 15:20 UTC, caternuson commented
Tested with a simple I2C scan and works. Could we do this somehow without needing a new file / function? The logic is pretty simple and looks like it could be done with a ternary. And just update i2c/spi/pin.py to use that.

2021-03-28 15:26 UTC, renpytom commented
I think it's just a little too complicated for a ternary, as one would have to first read the url into a variable, and then make a decision based on that variable.

If you think the additional file is unnecessary, then maybe it would make sense to put the get_ftdi_url function into adafruit_blinka/microcontroller/ft232h/__init__.py ?

2021-04-05 17:06 UTC, makermelissa commented
I see what @caternuson is asking. You could do something like:
```
self._spi.configure(url if url.startswith("ftdi:") else "ftdi://ftdi:ft232h/1")
```

2021-04-24 04:21 UTC, fharding1 commented
My two cents is that it makes sense to include another file for this.

There should be only one place where the constant `"BLINKA_FT232H"` exists. It would not make sense to define a `get_ftdi_url()` function in the i2c, spi, or pin file and use it from the others. So it belongs in it's own file.

I guess you could shorten the function to:

```python
def get_ftdi_url():
    """
    Return the FTDI url to use. If BLINKA_FT232H starts with ftdi:, returns
    that. Otherwise, returns a default value.
    """

    url = os.environ.get("BLINKA_FT232H", "1")
    return url if url.startswith("ftdi:") else "ftdi://ftdi:ft232h/1"
```

But this is a pretty insignificant change that's not worth much discussion in my opinion.

2021-05-04 22:33 UTC, caternuson commented
> There should be only one place where the constant "BLINKA_FT232H" exists.

There is. It only exists as an environment variable.

> It would not make sense to define a get_ftdi_url() function in the i2c, spi, or pin file and use it from the others.

The idea with the ternary is it gets rid of the need for that function and just does the equivalent logic in place. And therefore, gets rid of the need for the extra file.

2021-05-04 22:49 UTC, caternuson commented
If the concern is having references to the envvar `BLINKA_FT232H` in more than one place in the library code, then we could at least move the `get_ftdi_url` function into `__init__.py`. 

And then do a relative import in `i2c.py` and `spi.py`:
```python
 from . import get_ftdi_url
 ```

2021-05-04 22:59 UTC, fharding1 commented
> There is. It only exists as an environment variable.
> If the concern is having references to the envvar BLINKA_FT232H in more than one place in the library code

Yes, that was the concern expressed here: "there should be only one place where the constant `"BLINKA_FT232H"` exists"

> then we could at least move the get_ftdi_url function

Sure, I guess it could go in `__init__.py`.Not exactly where one would think to look, especially since most of them are empty in this project and they aren't really meant to have helper functions.

2021-05-05 19:41 UTC, caternuson requested changes

2021-05-05 19:41 UTC, caternuson commented on src/adafruit_blinka/microcontroller/ft232h/url.py
> +    return "ftdi://ftdi:ft232h/1"
Suggest moving this into `__init__.py` and then using a relative import in the other 3 .py files.

2021-05-07 20:46 UTC, caternuson commented
OK, want to get this done. Tried pushing those changes, but not allowed. Let's just merge this as is so other PRs can proceed. Can refactor later.

### Test Setup
![ft232h_test](https://user-images.githubusercontent.com/8755041/117506483-863c6100-af3a-11eb-86c2-b4eecd411ff4.jpg)

### Test program
```python
import time
import board
import digitalio

led = digitalio.DigitalInOut(board.C0)
led.direction = digitalio.Direction.OUTPUT

while True:
    led.value = not led.value
    time.sleep(1)
```

### Single Board
With a single FT232H attached, previous usage still works:
```
(blinka) $ export BLINKA_FT232H=1
(blinka) $ python3 blink.py
```
Which ever board is currently plugged in blinks.

### Multiple Boards
Plug in both FT232H's and then get URLs:
```python
>>> from pyftdi.ftdi import Ftdi
>>> Ftdi().open_from_url('ftdi:///?')
Available interfaces:
  ftdi://ftdi:232h:1/1          (￿￿￿￿￿￿)
  ftdi://ftdi:232h:FT2QJUM7/1   (USB <-> Serial Converter)
```

Can then specify URL to select FT232H to use:
```
(blinka) $ export BLINKA_FT232H=ftdi://ftdi:232h:1/1
(blinka) $ python3 blink.py
```
One board blinks.
```
(blinka) $ export BLINKA_FT232H=ftdi://ftdi:232h:FT2QJUM7/1
(blinka) $ python3 blink.py
```
Other board blinks.

2021-05-07 20:46 UTC, merged